# examples/terraform/main.tf
#
# A simple Terraform configuration using the local provider.
# This is used by the terraform_example.lua pipeline to demonstrate
# the full init -> plan -> apply -> output -> destroy lifecycle without
# requiring any cloud provider credentials.

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.2.3"
    }
  }
}

resource "local_file" "report" {
  content  = "This is a report generated by Terraform at ${timestamp()}."
  filename = "${path.module}/report.txt"
}

output "report_filename" {
  value       = local_file.report.filename
  description = "The full path to the generated report file."
}
