-- examples/artifact_example.lua
--
-- This pipeline demonstrates how to declare and produce artifacts.

TaskDefinitions = {
  artifact_management = {
    description = "Demonstrates artifact production and collection.",
    tasks = {
      {
        name = "create_artifact",
        description = "Creates a dummy file and declares it as an artifact.",
        command = function(params)
          local workdir = params.workdir
          local filename = "my_artifact.txt"
          local filepath = workdir .. "/" .. filename
          log.info("Creating dummy artifact: " .. filepath)
          fs.write(filepath, "This is a test artifact generated by sloth-runner.")
          log.info("Artifact created successfully.")
          return true, "Artifact created."
        end,
        artifacts = {
          "my_artifact.txt"
        }
      },
      {
        name = "create_another_artifact",
        description = "Creates another dummy file and declares it as an artifact.",
        command = function(params)
          local workdir = params.workdir
          local filename = "another_artifact.log"
          local filepath = workdir .. "/" .. filename
          log.info("Creating another dummy artifact: " .. filepath)
          fs.write(filepath, "This is another test artifact.\nIt's a log file.")
          log.info("Another artifact created successfully.")
          return true, "Another artifact created."
        end,
        artifacts = {
          "another_artifact.log"
        }
      }
    }
  }
}