
-- Task definitions for group: templated-task
-- Generated by: sloth-runner new (template: simple)
TaskDefinitions = {
  ["templated-task"] = {
    description = "TODO: Add a description for the templated-task task group.",
    tasks = {
      {
        name = "hello_task",
        description = "An example task. Modify or add new tasks here.",
        command = function(params)
          local workdir = params.workdir
          log.info("Running example task for group templated-task in: " .. workdir)
          log.info("Custom message: Hello from templated task!") -- Added for demonstration
          local stdout, stderr, err = exec.command("echo 'Hello from sloth-runner!'")
          if err then
            log.error("Failed to run example task: " .. stderr)
            return false, "Dummy task failed."
          else
            log.info("Example task completed successfully.")
            print("Command output: " .. stdout)
            return true, "Dummy task executed successfully."
          end
        end
      }
    }
  }
}
